modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"
issueTrackerURL="https://github.com/GG-II/Libunand-Mod"

[[mods]]
modId="libunand"
version="1.0.0"
displayName="Libunand"
updateJSONURL=""
displayURL="https://github.com/GG-II/Libunand-Mod"
logoFile="logo.png"
credits="Desarrollado por ABFann"
authors="ABFann"
description='''
Sistema economico completo con JoJoCoins para Minecraft.

Caracteristicas:
- Moneda personalizada JoJoCoin que reemplaza esmeraldas
- Sistema de tiendas jugador-a-jugador con carteles
- Cofres vinculados con particulas
- Comandos de economia completos
- Compatible con WorldEdit y WorldProtection
'''

[[dependencies.libunand]]
modId="forge"
mandatory=true
versionRange="[36,)"
ordering="NONE"
side="BOTH"

[[dependencies.libunand]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5]"
ordering="NONE"
side="BOTH"